---
  - name: Update all the things
    hosts:
        - servers
        - rasbpi
    become: True
    tasks:
      - name: apt
        apt:
          update_cache: yes
          upgrade: 'yes'
