---
  - name: Install qemu-guest-agent
    hosts: "*"
    tasks:
      - name: Instal qemu-guest-agent
        apt:
          name: qemu-guest-agent
          state: present
          update_cache: true
        become: true
